### ISSUE TITLE
As PSD developers we would like to investigate the possibility of moving the printers to a database table or another option so that we can easily change the label type without having to deploy

### ISSUE THREAD

**Issue by stevieing** [sanger/sprint#68]
**Description**
As PSD developers we would like to investigate the possibility of moving the printers to a database table or another option so that we can easily change the label type without having to deploy.

We have just bought a couple of printers for testing. We would like to regularly swap out the labels. We have named the printers generically to that end. The other week we tried to do this and realised that we would need to make changes to sprint and then deploy so we swapped back.

**Who the primary contacts are for this work**
Steve

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by khelwood** [comment]
We already can change the label type of a printer in SPrint without having to deploy. The printers are described in config. We can update the config, and tell SPrint to reload the config.

**Comment by stevieing** [comment]
> We already can change the label type of a printer in SPrint without having to deploy. The printers are described in config. We can update the config, and tell SPrint to reload the config. It was written specifically to allow this.

Ok. Great. Are there instructions in the readme?

**Comment by khelwood** [comment]
I'll add some clearer instructions.

**Comment by khelwood** [comment]
I've added some instructions to the sprint-deployment README.
You also have the option of including the label size in the print request, so you can use different label sizes on a printer without updating the config at all. There is an optional `labelSize` field in the `PrintRequest.Layout` object.

**Comment by stevieing** [comment]
> I've added some instructions to the sprint-deployment README. You also have the option of including the label size in the print request, so you can use different label sizes on a printer without updating the config at all. There is an optional `labelSize` field in the `PrintRequest.Layout` object.

Thanks David.

**Comment by stevieing** [comment]
Closed as done. Instructions added to sprint-deployment README
